### ISSUE TITLE
animatplot.testing is not installed

### ISSUE THREAD

**Issue by QuLogic** [t-makaro/animatplot#25]
It appears that the `animatplot.testing` package is not installed; this means that tests cannot be run against an installed copy because the import doesn't work.

**Comment by t-makaro** [comment]
Neither the testing tools nor the tests themselves are packaged into an installation. I didn't want ```animatplot.testing``` to be a part of the API, and I figured that anyone running tests would use an editable install.

**Comment by t-makaro** [comment]
Ah. I see. Moving the testing tools into the ```tests``` directory seems reasonable to me.
