### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by t-makaro** [t-makaro/animatplot#4]
While this is a pure python package, pip likes to mangle conda packages sometimes. So, if someone tries to install Animatplot with a version of matplotlib < 2.2 which was installed with conda, then pip attempts to update matplotlib and butcher the environment (sometimes multiple since conda symlinks packages of the same version across environments).

I'd like to be able to install Animatplot with conda.

**Comment by TomNicholas** [comment]
Let me know if I can help with this - I haven't added a package to conda before but I would like to learn how.

I also need animatplot to be available on conda in order to build it within xarray's CI test suites, which is necessary for animatplot to become an optional dependency of xarray.

**Comment by t-makaro** [comment]
I started this process over at: https://github.com/conda-forge/staged-recipes/pull/7706

**Comment by TomNicholas** [comment]
I think this should have been version 0.4.0 uploaded to conda instead of 0.3.0?

**Comment by TomNicholas** [comment]
Ah right I didn't realise that the Title block PR had been merged into master but not included in 0.3.0. Is it possible to add that feature to the conda-forge feedstock by updating to 0.3.1 or something? (Adding an extra block should be a backwards-compatible change)

**Comment by t-makaro** [comment]
I'll publish version 0.4.0 in the next few days.
