### ISSUE TITLE
incompatibility with pcolormesh `shading="nearest"` option in matplotlib-3.3

### ISSUE THREAD

**Issue by johnomotani** [t-makaro/animatplot#52]
Adapting the `pcolormesh` example, and using the new `shading="nearest"` option from matplotlib-3.3.2
```
import numpy as np
import matplotlib.pyplot as plt
import animatplot as amp


x = np.linspace(-2, 2, 50)
y = np.linspace(-2, 2, 50)
t = np.linspace(0, 2*np.pi, 40)

X, Y, T = np.meshgrid(x, y, t)

Z = np.sin(X*X+Y*Y-T)

shading = "nearest"
#shading = "flat"
block = amp.blocks.Pcolormesh(X[:,:,0], Y[:,:,0], Z, t_axis=2, cmap='RdBu', shading=shading)
plt.colorbar(block.quad)
plt.gca().set_aspect('equal')

anim = amp.Animation([block], amp.Timeline(t))

anim.controls()

anim.save_gif('pcolormesh')
plt.show()
```
 gives
![pcolormesh](https://user-images.githubusercontent.com/3958036/94285082-295fdd80-ff4b-11ea-9120-17fd76102d01.gif)

instead of the expected result, which we get with `shading="flat"`
![pcolormesh](https://user-images.githubusercontent.com/3958036/94285273-5dd39980-ff4b-11ea-9660-1f98c02b23ba.gif)

I suspect this is related to flattening the array here https://github.com/t-makaro/animatplot/blob/632d988687fca7e7415e9fa49fe7eebc3f0991c6/animatplot/blocks/image_like.py#L57-L60

**Comment by t-makaro** [comment]
Closed by #53
