### ISSUE TITLE
blocks.Pcolormesh seems to have different behavior than plt.pcolormesh

### ISSUE THREAD

**Issue by Xin-yang-Liu** [t-makaro/animatplot#56]
I am not sure if it is a feature or a bug.
When I was playing with the example code:

```
import numpy as np
import matplotlib.pyplot as plt
import animatplot as amp


x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)
t = np.linspace(0, 2*np.pi, 40)

X, Y, T = np.meshgrid(x, y, t)

Z = np.sin(X*X+Y*Y-T)

block = amp.blocks.Pcolormesh(X[:,:,0], Y[:,:,0], Z, t_axis=2, cmap='RdBu')
plt.colorbar(block.quad)
plt.gca().set_aspect('equal')

anim = amp.Animation([block], amp.Timeline(t))

anim.controls()
plt.show()
```

I used a very coarse grid 5*5 instead of the original 50*50, so that it is more clear.
The data array `Z` is of size 5*5 at a certain time step. But the generated animation shows a grid of shape 4*4.
It seems blocks.Pcolormesh use the value in `Z` as the "node" value in animation, which is different in plt.pcolormesh where`Z` value is treated as the "mesh cell" value.

**Comment by johnomotani** [comment]
What versions of animatplot and matplotlib are you using? For me with animatplot-0.4.2 and matplotlib-3.3.3, from the following the pcolormesh plot is identical (apart from tick labels) to the first frame of the animation.
```
import numpy as np
import matplotlib.pyplot as plt
import animatplot as amp


x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)
t = np.linspace(0, 2*np.pi, 40)

X, Y, T = np.meshgrid(x, y, t)

Z = np.sin(X*X+Y*Y-T)

plt.pcolormesh(X[:,:,0], Y[:,:,0], Z[:,:,0], cmap='RdBu')
plt.colorbar()


plt.figure()

block = amp.blocks.Pcolormesh(X[:,:,0], Y[:,:,0], Z, t_axis=2, cmap='RdBu')
plt.colorbar(block.quad)
plt.gca().set_aspect('equal')

anim = amp.Animation([block], amp.Timeline(t))

anim.controls()
plt.show()
```

We did change `Pcolormesh` recently though: #53

**Comment by Xin-yang-Liu** [comment]
I am using the exact same version of animatplot and matplotlib as you. 
![plt](https://user-images.githubusercontent.com/44840526/101213366-45b58000-3648-11eb-85e4-e9a0125a4973.png)
![pcolormesh](https://user-images.githubusercontent.com/44840526/101213387-4e0dbb00-3648-11eb-8b23-ecca00c56769.gif)
the first figure is generated using plt.pcolormesh at time 0. The grid is 5 by 5.
In the animation, the grid is 4*4

**Comment by johnomotani** [comment]
Have you changed the default value of `matplotlib.rcParams["pcolor.shading"]? Your output is what I get with `plt.pcolormesh(X[:,:,0], Y[:,:,0], Z[:,:,0], shading="nearest")`. `shading="nearest"` will become the matplotlib default at some point, but for the moment the default is still `shading="flat"`. We should pick up the default from matplotlib though, here https://github.com/t-makaro/animatplot/blob/26b3c794e5901f826933b05b29f76512a97debf0/animatplot/blocks/image_like.py#L56
so I'm confused.

animatplot is behaving as I'd expect, it's your matplotlib plot that seems odd. Maybe you could try creating a clean virtual environment (or conda environment) and make the `plt.pcolormesh` plot again?

**Comment by Xin-yang-Liu** [comment]
I did not change any default value. 
Actually, I also tried in a clean conda environment (python 3.7.8, matplotlib 3.3.3, numpy 1.19.4) and got the same figure.

**Comment by Xin-yang-Liu** [comment]
Actually I was using `plt.pcolormesh(Z[:,:,0])` and got the figure with `shading="nearest"`(5 * 5 grid) by default
Besides, I tried `plt.pcolormesh(X[:,:,0],Y[:,:,0],Z[:,:,0])`. It seems the default value becomes `shading="flat"` (4 * 4 grid)

**Comment by johnomotani** [comment]
animatplot at the moment doesn't support calling like `Pcolormesh(Z)` without `X` and `Y` arrays. I think a PR adding that functionality would be welcome.

The current behaviour is consistent with matplotlib's `pcolormesh` when passing `X`, `Y` and `Z`, so this isn't a bug. The matplotlib behaviour without `X` and `Y` arguments is like calling (if `Z` is an array of shape `(n,m)`)
```
plt.pcolormesh(np.arange(m+1), np.arange(n+1), Z)
```
