### ISSUE TITLE
BunchOfFiles writer incompatible with matplotlib-3.4

### ISSUE THREAD

**Issue by johnomotani** [t-makaro/animatplot#58]
The implementation of `matplotlib.animation.FileMovieWriter` seems to have changed in matplotlib-3.4, and the `_frame_sink` member no longer exists. This makes the unit tests fail. I guess `BunchOfFiles` needs to be updated, maybe following the patters in `matplotlib.animation` https://matplotlib.org/stable/_modules/matplotlib/animation.html?

**Comment by t-makaro** [comment]
Relevant Matplotlib change: https://github.com/matplotlib/matplotlib/pull/19045

**Comment by t-makaro** [comment]
Looks like a straight swap of ```_frame_sink``` with ```self._proc.stdin```, and maybe removing the ```finish()``` function. Looks like this will be backwards compatible with older matplotlib too.

**Comment by t-makaro** [comment]
I'm looking at fixing this within the next few days. It's top priority before I can do anything else.
